version: "1"
services:
  # FastAPI backend running on a free Web Service
  - type: web
    name: backend
    runtime: python
    plan: free
    buildCommand: |
      # Install backend dependencies
      pip install --upgrade pip
      pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9

  # Next.js frontend running as a Node web service (SSR)
  - type: web
    name: frontend
    runtime: node
    buildCommand: |
      cd next
      yarn install --silent
      yarn build
    startCommand: next start -p $PORT
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 18.20.0
      - key: BASE_URL
        value: https://frontend-weqm.onrender.com
      - key: NEXT_PUBLIC_BACKEND_URL
        fromService:
          type: web
          name: backend
          property: hostport